# from https://github.com/espm-157/reproducibility-template
# devcontainer-focused Rocker
FROM ghcr.io/rocker-org/devcontainer/geospatial:4.2

# must be in .devcontainer dir
# RUN R -e 'if(file.exists("install.R")) source("install.R")'
